name: API linting

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Run linting
        run: |
          redocly lint docs/openapi.yml --format=github-actions
